<?php

define('WWW_DIR', dirname(__DIR__));
define('APP_DIR', __DIR__);

// Load Nette Framework or autoloader generated by Composer
require WWW_DIR . '/libs/autoload.php';


$configurator = new Nette\Config\Configurator;

// Enable Nette Debugger for error visualisation & logging
//$configurator->setDebugMode(TRUE);
$configurator->enableDebugger(WWW_DIR . '/log');

// Specify folder for cache
$configurator->setTempDirectory(WWW_DIR . '/temp');

// Enable RobotLoader - this will load all classes automatically
$configurator->createRobotLoader()
	->addDirectory(APP_DIR)
	->addDirectory(WWW_DIR . '/libs')
	->register();

// Create Dependency Injection container from config.neon file
$configurator->addConfig(APP_DIR . '/config/config.neon');
$localConfig = APP_DIR . '/config/config.local.neon';
if (file_exists($localConfig))
{
    $configurator->addConfig($localConfig, $configurator::NONE); // none section
}

$container = $configurator->createContainer();

return $container;
